// biome-ignore-all format: generated file
import { describe, expect, it } from "vitest";
import { compileEcmaRe } from "./helpers";

// Generated by scripts/update-cpython-tests.mjs from:
// https://cdn.jsdelivr.net/gh/python/cpython@main/Lib/test/re_tests.py
// Do not edit this file by hand.

const SUCCEED = 0;
const FAIL = 1;
const SYNTAX_ERROR = 2;

type Outcome = typeof SUCCEED | typeof FAIL | typeof SYNTAX_ERROR;

type CpythonReCase = {
  pattern: string;
  input: string;
  outcome: Outcome;
  expr?: string;
  expected?: string;
};

const CPYTHON_RE_TESTS: CpythonReCase[] = [
  { pattern: "(?P<foo_123", input: "", outcome: SYNTAX_ERROR },
  { pattern: "(?P<1>a)", input: "", outcome: SYNTAX_ERROR },
  { pattern: "(?P<!>a)", input: "", outcome: SYNTAX_ERROR },
  { pattern: "(?P<foo!>a)", input: "", outcome: SYNTAX_ERROR },
  { pattern: "(?P<foo_123>a)(?P=foo_123", input: "aa", outcome: SYNTAX_ERROR },
  { pattern: "(?P<foo_123>a)(?P=1)", input: "aa", outcome: SYNTAX_ERROR },
  { pattern: "(?P<foo_123>a)(?P=!)", input: "aa", outcome: SYNTAX_ERROR },
  { pattern: "(?P<foo_123>a)(?P=foo_124", input: "aa", outcome: SYNTAX_ERROR },
  { pattern: "(?P<foo_123>a)", input: "a", outcome: SUCCEED, expr: "g1", expected: "a" },
  { pattern: "(?P<foo_123>a)(?P=foo_123)", input: "aa", outcome: SUCCEED, expr: "g1", expected: "a" },
  { pattern: "\\1", input: "a", outcome: SYNTAX_ERROR },
  { pattern: "[\\1]", input: "\u0001", outcome: SUCCEED, expr: "found", expected: "\u0001" },
  { pattern: "\\09", input: "\u00009", outcome: SUCCEED, expr: "found", expected: "\u00009" },
  { pattern: "\\141", input: "a", outcome: SUCCEED, expr: "found", expected: "a" },
  { pattern: "(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)\\119", input: "abcdefghijklk9", outcome: SUCCEED, expr: "found+\"-\"+g11", expected: "abcdefghijklk9-k" },
  { pattern: "\\0", input: "\u0000", outcome: SUCCEED, expr: "found", expected: "\u0000" },
  { pattern: "[\\0a]", input: "\u0000", outcome: SUCCEED, expr: "found", expected: "\u0000" },
  { pattern: "[a\\0]", input: "\u0000", outcome: SUCCEED, expr: "found", expected: "\u0000" },
  { pattern: "[^a\\0]", input: "\u0000", outcome: FAIL },
  { pattern: "\\a[\\b]\\f\\n\\r\\t\\v", input: "\u0007\b\f\n\r\t\u000b", outcome: SUCCEED, expr: "found", expected: "\u0007\b\f\n\r\t\u000b" },
  { pattern: "[\\a][\\b][\\f][\\n][\\r][\\t][\\v]", input: "\u0007\b\f\n\r\t\u000b", outcome: SUCCEED, expr: "found", expected: "\u0007\b\f\n\r\t\u000b" },
  { pattern: "\\u", input: "", outcome: SYNTAX_ERROR },
  { pattern: "\\x00ffffffffffffff", input: "ÿ", outcome: FAIL, expr: "found", expected: "ÿ" },
  { pattern: "\\x00f", input: "\u000f", outcome: FAIL, expr: "found", expected: "\u000f" },
  { pattern: "\\x00fe", input: "þ", outcome: FAIL, expr: "found", expected: "þ" },
  { pattern: "^\\w+=(\\\\[\\000-\\277]|[^\\n\\\\])*", input: "SRC=eval.c g.c blah blah blah \\\\\n\tapes.c", outcome: SUCCEED, expr: "found", expected: "SRC=eval.c g.c blah blah blah \\\\" },
  { pattern: "a.b", input: "acb", outcome: SUCCEED, expr: "found", expected: "acb" },
  { pattern: "a.b", input: "a\nb", outcome: FAIL },
  { pattern: "a.*b", input: "acc\nccb", outcome: FAIL },
  { pattern: "a.{4,5}b", input: "acc\nccb", outcome: FAIL },
  { pattern: "a.b", input: "a\rb", outcome: SUCCEED, expr: "found", expected: "a\rb" },
  { pattern: "(?s)a.b", input: "a\nb", outcome: SUCCEED, expr: "found", expected: "a\nb" },
  { pattern: "(?s)a.*b", input: "acc\nccb", outcome: SUCCEED, expr: "found", expected: "acc\nccb" },
  { pattern: "(?s)a.{4,5}b", input: "acc\nccb", outcome: SUCCEED, expr: "found", expected: "acc\nccb" },
  { pattern: "(?s)a.b", input: "a\rb", outcome: SUCCEED, expr: "found", expected: "a\rb" },
  { pattern: ")", input: "", outcome: SYNTAX_ERROR },
  { pattern: "", input: "", outcome: SUCCEED, expr: "found", expected: "" },
  { pattern: "abc", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "abc", input: "xbc", outcome: FAIL },
  { pattern: "abc", input: "axc", outcome: FAIL },
  { pattern: "abc", input: "abx", outcome: FAIL },
  { pattern: "abc", input: "xabcy", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "abc", input: "ababc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "ab*c", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "ab*bc", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "ab*bc", input: "abbc", outcome: SUCCEED, expr: "found", expected: "abbc" },
  { pattern: "ab*bc", input: "abbbbc", outcome: SUCCEED, expr: "found", expected: "abbbbc" },
  { pattern: "ab+bc", input: "abbc", outcome: SUCCEED, expr: "found", expected: "abbc" },
  { pattern: "ab+bc", input: "abc", outcome: FAIL },
  { pattern: "ab+bc", input: "abq", outcome: FAIL },
  { pattern: "ab+bc", input: "abbbbc", outcome: SUCCEED, expr: "found", expected: "abbbbc" },
  { pattern: "ab?bc", input: "abbc", outcome: SUCCEED, expr: "found", expected: "abbc" },
  { pattern: "ab?bc", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "ab?bc", input: "abbbbc", outcome: FAIL },
  { pattern: "ab?c", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "^abc$", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "^abc$", input: "abcc", outcome: FAIL },
  { pattern: "^abc", input: "abcc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "^abc$", input: "aabc", outcome: FAIL },
  { pattern: "abc$", input: "aabc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "^", input: "abc", outcome: SUCCEED, expr: "found+\"-\"", expected: "-" },
  { pattern: "$", input: "abc", outcome: SUCCEED, expr: "found+\"-\"", expected: "-" },
  { pattern: "a.c", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "a.c", input: "axc", outcome: SUCCEED, expr: "found", expected: "axc" },
  { pattern: "a.*c", input: "axyzc", outcome: SUCCEED, expr: "found", expected: "axyzc" },
  { pattern: "a.*c", input: "axyzd", outcome: FAIL },
  { pattern: "a[bc]d", input: "abc", outcome: FAIL },
  { pattern: "a[bc]d", input: "abd", outcome: SUCCEED, expr: "found", expected: "abd" },
  { pattern: "a[b-d]e", input: "abd", outcome: FAIL },
  { pattern: "a[b-d]e", input: "ace", outcome: SUCCEED, expr: "found", expected: "ace" },
  { pattern: "a[b-d]", input: "aac", outcome: SUCCEED, expr: "found", expected: "ac" },
  { pattern: "a[-b]", input: "a-", outcome: SUCCEED, expr: "found", expected: "a-" },
  { pattern: "a[\\-b]", input: "a-", outcome: SUCCEED, expr: "found", expected: "a-" },
  { pattern: "a[]b", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "a[", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "a\\", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "abc)", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(abc", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "a]", input: "a]", outcome: SUCCEED, expr: "found", expected: "a]" },
  { pattern: "a[]]b", input: "a]b", outcome: SUCCEED, expr: "found", expected: "a]b" },
  { pattern: "a[\\]]b", input: "a]b", outcome: SUCCEED, expr: "found", expected: "a]b" },
  { pattern: "a[^bc]d", input: "aed", outcome: SUCCEED, expr: "found", expected: "aed" },
  { pattern: "a[^bc]d", input: "abd", outcome: FAIL },
  { pattern: "a[^-b]c", input: "adc", outcome: SUCCEED, expr: "found", expected: "adc" },
  { pattern: "a[^-b]c", input: "a-c", outcome: FAIL },
  { pattern: "a[^]b]c", input: "a]c", outcome: FAIL },
  { pattern: "a[^]b]c", input: "adc", outcome: SUCCEED, expr: "found", expected: "adc" },
  { pattern: "\\ba\\b", input: "a-", outcome: SUCCEED, expr: "\"-\"", expected: "-" },
  { pattern: "\\ba\\b", input: "-a", outcome: SUCCEED, expr: "\"-\"", expected: "-" },
  { pattern: "\\ba\\b", input: "-a-", outcome: SUCCEED, expr: "\"-\"", expected: "-" },
  { pattern: "\\by\\b", input: "xy", outcome: FAIL },
  { pattern: "\\by\\b", input: "yz", outcome: FAIL },
  { pattern: "\\by\\b", input: "xyz", outcome: FAIL },
  { pattern: "x\\b", input: "xyz", outcome: FAIL },
  { pattern: "x\\B", input: "xyz", outcome: SUCCEED, expr: "\"-\"", expected: "-" },
  { pattern: "\\Bz", input: "xyz", outcome: SUCCEED, expr: "\"-\"", expected: "-" },
  { pattern: "z\\B", input: "xyz", outcome: FAIL },
  { pattern: "\\Bx", input: "xyz", outcome: FAIL },
  { pattern: "\\Ba\\B", input: "a-", outcome: FAIL, expr: "\"-\"", expected: "-" },
  { pattern: "\\Ba\\B", input: "-a", outcome: FAIL, expr: "\"-\"", expected: "-" },
  { pattern: "\\Ba\\B", input: "-a-", outcome: FAIL, expr: "\"-\"", expected: "-" },
  { pattern: "\\By\\B", input: "xy", outcome: FAIL },
  { pattern: "\\By\\B", input: "yz", outcome: FAIL },
  { pattern: "\\By\\b", input: "xy", outcome: SUCCEED, expr: "\"-\"", expected: "-" },
  { pattern: "\\by\\B", input: "yz", outcome: SUCCEED, expr: "\"-\"", expected: "-" },
  { pattern: "\\By\\B", input: "xyz", outcome: SUCCEED, expr: "\"-\"", expected: "-" },
  { pattern: "ab|cd", input: "abc", outcome: SUCCEED, expr: "found", expected: "ab" },
  { pattern: "ab|cd", input: "abcd", outcome: SUCCEED, expr: "found", expected: "ab" },
  { pattern: "()ef", input: "def", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ef-" },
  { pattern: "$b", input: "b", outcome: FAIL },
  { pattern: "a\\(b", input: "a(b", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "a(b-Error" },
  { pattern: "a\\(*b", input: "ab", outcome: SUCCEED, expr: "found", expected: "ab" },
  { pattern: "a\\(*b", input: "a((b", outcome: SUCCEED, expr: "found", expected: "a((b" },
  { pattern: "a\\\\b", input: "a\\b", outcome: SUCCEED, expr: "found", expected: "a\\b" },
  { pattern: "((a))", input: "abc", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "a-a-a" },
  { pattern: "(a)b(c)", input: "abc", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "abc-a-c" },
  { pattern: "a+b+c", input: "aabbabc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "(a+|b)*", input: "ab", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ab-b" },
  { pattern: "(a+|b)+", input: "ab", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ab-b" },
  { pattern: "(a+|b)?", input: "ab", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "a-a" },
  { pattern: ")(", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "[^ab]*", input: "cde", outcome: SUCCEED, expr: "found", expected: "cde" },
  { pattern: "abc", input: "", outcome: FAIL },
  { pattern: "a*", input: "", outcome: SUCCEED, expr: "found", expected: "" },
  { pattern: "a|b|c|d|e", input: "e", outcome: SUCCEED, expr: "found", expected: "e" },
  { pattern: "(a|b|c|d|e)f", input: "ef", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ef-e" },
  { pattern: "abcd*efg", input: "abcdefg", outcome: SUCCEED, expr: "found", expected: "abcdefg" },
  { pattern: "ab*", input: "xabyabbbz", outcome: SUCCEED, expr: "found", expected: "ab" },
  { pattern: "ab*", input: "xayabbbz", outcome: SUCCEED, expr: "found", expected: "a" },
  { pattern: "(ab|cd)e", input: "abcde", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "cde-cd" },
  { pattern: "[abhgefdc]ij", input: "hij", outcome: SUCCEED, expr: "found", expected: "hij" },
  { pattern: "^(ab|cd)e", input: "abcde", outcome: FAIL, expr: "xg1y", expected: "xy" },
  { pattern: "(abc|)ef", input: "abcdef", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ef-" },
  { pattern: "(a|b)c*d", input: "abcd", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "bcd-b" },
  { pattern: "(ab|ab*)bc", input: "abc", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abc-a" },
  { pattern: "a([bc]*)c*", input: "abc", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abc-bc" },
  { pattern: "a([bc]*)(c*d)", input: "abcd", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "abcd-bc-d" },
  { pattern: "a([bc]+)(c*d)", input: "abcd", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "abcd-bc-d" },
  { pattern: "a([bc]*)(c+d)", input: "abcd", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "abcd-b-cd" },
  { pattern: "a[bcd]*dcdcde", input: "adcdcde", outcome: SUCCEED, expr: "found", expected: "adcdcde" },
  { pattern: "a[bcd]+dcdcde", input: "adcdcde", outcome: FAIL },
  { pattern: "(ab|a)b*c", input: "abc", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abc-ab" },
  { pattern: "((a)(b)c)(d)", input: "abcd", outcome: SUCCEED, expr: "g1+\"-\"+g2+\"-\"+g3+\"-\"+g4", expected: "abc-a-b-d" },
  { pattern: "[a-zA-Z_][a-zA-Z0-9_]*", input: "alpha", outcome: SUCCEED, expr: "found", expected: "alpha" },
  { pattern: "^a(bc+|b[eh])g|.h$", input: "abh", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "bh-None" },
  { pattern: "(bc+d$|ef*g.|h?i(j|k))", input: "effgz", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "effgz-effgz-None" },
  { pattern: "(bc+d$|ef*g.|h?i(j|k))", input: "ij", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "ij-ij-j" },
  { pattern: "(bc+d$|ef*g.|h?i(j|k))", input: "effg", outcome: FAIL },
  { pattern: "(bc+d$|ef*g.|h?i(j|k))", input: "bcdd", outcome: FAIL },
  { pattern: "(bc+d$|ef*g.|h?i(j|k))", input: "reffgz", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "effgz-effgz-None" },
  { pattern: "(((((((((a)))))))))", input: "a", outcome: SUCCEED, expr: "found", expected: "a" },
  { pattern: "multiple words of text", input: "uh-uh", outcome: FAIL },
  { pattern: "multiple words", input: "multiple words, yeah", outcome: SUCCEED, expr: "found", expected: "multiple words" },
  { pattern: "(.*)c(.*)", input: "abcde", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "abcde-ab-de" },
  { pattern: "\\((.*), (.*)\\)", input: "(a, b)", outcome: SUCCEED, expr: "g2+\"-\"+g1", expected: "b-a" },
  { pattern: "[k]", input: "ab", outcome: FAIL },
  { pattern: "a[-]?c", input: "ac", outcome: SUCCEED, expr: "found", expected: "ac" },
  { pattern: "(abc)\\1", input: "abcabc", outcome: SUCCEED, expr: "g1", expected: "abc" },
  { pattern: "([a-c]*)\\1", input: "abcabc", outcome: SUCCEED, expr: "g1", expected: "abc" },
  { pattern: "^(.+)?B", input: "AB", outcome: SUCCEED, expr: "g1", expected: "A" },
  { pattern: "(a+).\\1$", input: "aaaaa", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aaaaa-aa" },
  { pattern: "^(a+).\\1$", input: "aaaa", outcome: FAIL },
  { pattern: "(abc)\\1", input: "abcabc", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abcabc-abc" },
  { pattern: "([a-c]+)\\1", input: "abcabc", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abcabc-abc" },
  { pattern: "(a)\\1", input: "aa", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aa-a" },
  { pattern: "(a+)\\1", input: "aa", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aa-a" },
  { pattern: "(a+)+\\1", input: "aa", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aa-a" },
  { pattern: "(a).+\\1", input: "aba", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aba-a" },
  { pattern: "(a)ba*\\1", input: "aba", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aba-a" },
  { pattern: "(aa|a)a\\1$", input: "aaa", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aaa-a" },
  { pattern: "(a|aa)a\\1$", input: "aaa", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aaa-a" },
  { pattern: "(a+)a\\1$", input: "aaa", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aaa-a" },
  { pattern: "([abc]*)\\1", input: "abcabc", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abcabc-abc" },
  { pattern: "(a)(b)c|ab", input: "ab", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "ab-None-None" },
  { pattern: "(a)+x", input: "aaax", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aaax-a" },
  { pattern: "([ac])+x", input: "aacx", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aacx-c" },
  { pattern: "([^/]*/)*sub1/", input: "d:msgs/tdir/sub1/trial/away.cpp", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "d:msgs/tdir/sub1/-tdir/" },
  { pattern: "([^.]*)\\.([^:]*):[T ]+(.*)", input: "track1.title:TBlah blah blah", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2+\"-\"+g3", expected: "track1.title:TBlah blah blah-track1-title-Blah blah blah" },
  { pattern: "([^N]*N)+", input: "abNNxyzN", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abNNxyzN-xyzN" },
  { pattern: "([^N]*N)+", input: "abNNxyz", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abNN-N" },
  { pattern: "([abc]*)x", input: "abcx", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abcx-abc" },
  { pattern: "([abc]*)x", input: "abc", outcome: FAIL },
  { pattern: "([xyz]*)x", input: "abcx", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "x-" },
  { pattern: "(a)+b|aac", input: "aac", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "aac-None" },
  { pattern: "(?P<i d>aaa)a", input: "aaaa", outcome: SYNTAX_ERROR },
  { pattern: "(?P<id>aaa)a", input: "aaaa", outcome: SUCCEED, expr: "found+\"-\"+id", expected: "aaaa-aaa" },
  { pattern: "(?P<id>aa)(?P=id)", input: "aaaa", outcome: SUCCEED, expr: "found+\"-\"+id", expected: "aaaa-aa" },
  { pattern: "(?P<id>aa)(?P=xd)", input: "aaaa", outcome: SYNTAX_ERROR },
  { pattern: "\\1", input: "a", outcome: SYNTAX_ERROR },
  { pattern: "ab{0,}bc", input: "abbbbc", outcome: SUCCEED, expr: "found", expected: "abbbbc" },
  { pattern: "ab{1,}bc", input: "abq", outcome: FAIL },
  { pattern: "ab{1,}bc", input: "abbbbc", outcome: SUCCEED, expr: "found", expected: "abbbbc" },
  { pattern: "ab{1,3}bc", input: "abbbbc", outcome: SUCCEED, expr: "found", expected: "abbbbc" },
  { pattern: "ab{3,4}bc", input: "abbbbc", outcome: SUCCEED, expr: "found", expected: "abbbbc" },
  { pattern: "ab{4,5}bc", input: "abbbbc", outcome: FAIL },
  { pattern: "ab{0,1}bc", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "ab{0,1}c", input: "abc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "^", input: "abc", outcome: SUCCEED, expr: "found", expected: "" },
  { pattern: "$", input: "abc", outcome: SUCCEED, expr: "found", expected: "" },
  { pattern: "a[b-]", input: "a-", outcome: SUCCEED, expr: "found", expected: "a-" },
  { pattern: "a[b-a]", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "*a", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(*)b", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "a{1,}b{1,}c", input: "aabbabc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "a**", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "a.+?c", input: "abcabc", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "(a+|b){0,}", input: "ab", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ab-b" },
  { pattern: "(a+|b){1,}", input: "ab", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ab-b" },
  { pattern: "(a+|b){0,1}", input: "ab", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "a-a" },
  { pattern: "([abc])*d", input: "abbbcd", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abbbcd-c" },
  { pattern: "([abc])*bcd", input: "abcd", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "abcd-a" },
  { pattern: "^(ab|cd)e", input: "abcde", outcome: FAIL },
  { pattern: "((((((((((a))))))))))", input: "a", outcome: SUCCEED, expr: "g10", expected: "a" },
  { pattern: "((((((((((a))))))))))\\10", input: "aa", outcome: SUCCEED, expr: "found", expected: "aa" },
  { pattern: "((((((((((a))))))))))\\41", input: "", outcome: SYNTAX_ERROR },
  { pattern: "(?i)((((((((((a))))))))))\\41", input: "", outcome: SYNTAX_ERROR },
  { pattern: "(?i)abc", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)abc", input: "XBC", outcome: FAIL },
  { pattern: "(?i)abc", input: "AXC", outcome: FAIL },
  { pattern: "(?i)abc", input: "ABX", outcome: FAIL },
  { pattern: "(?i)abc", input: "XABCY", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)abc", input: "ABABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)ab*c", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)ab*bc", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)ab*bc", input: "ABBC", outcome: SUCCEED, expr: "found", expected: "ABBC" },
  { pattern: "(?i)ab*?bc", input: "ABBBBC", outcome: SUCCEED, expr: "found", expected: "ABBBBC" },
  { pattern: "(?i)ab{0,}?bc", input: "ABBBBC", outcome: SUCCEED, expr: "found", expected: "ABBBBC" },
  { pattern: "(?i)ab+?bc", input: "ABBC", outcome: SUCCEED, expr: "found", expected: "ABBC" },
  { pattern: "(?i)ab+bc", input: "ABC", outcome: FAIL },
  { pattern: "(?i)ab+bc", input: "ABQ", outcome: FAIL },
  { pattern: "(?i)ab{1,}bc", input: "ABQ", outcome: FAIL },
  { pattern: "(?i)ab+bc", input: "ABBBBC", outcome: SUCCEED, expr: "found", expected: "ABBBBC" },
  { pattern: "(?i)ab{1,}?bc", input: "ABBBBC", outcome: SUCCEED, expr: "found", expected: "ABBBBC" },
  { pattern: "(?i)ab{1,3}?bc", input: "ABBBBC", outcome: SUCCEED, expr: "found", expected: "ABBBBC" },
  { pattern: "(?i)ab{3,4}?bc", input: "ABBBBC", outcome: SUCCEED, expr: "found", expected: "ABBBBC" },
  { pattern: "(?i)ab{4,5}?bc", input: "ABBBBC", outcome: FAIL },
  { pattern: "(?i)ab??bc", input: "ABBC", outcome: SUCCEED, expr: "found", expected: "ABBC" },
  { pattern: "(?i)ab??bc", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)ab{0,1}?bc", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)ab??bc", input: "ABBBBC", outcome: FAIL },
  { pattern: "(?i)ab??c", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)ab{0,1}?c", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)^abc$", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)^abc$", input: "ABCC", outcome: FAIL },
  { pattern: "(?i)^abc", input: "ABCC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)^abc$", input: "AABC", outcome: FAIL },
  { pattern: "(?i)abc$", input: "AABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)^", input: "ABC", outcome: SUCCEED, expr: "found", expected: "" },
  { pattern: "(?i)$", input: "ABC", outcome: SUCCEED, expr: "found", expected: "" },
  { pattern: "(?i)a.c", input: "ABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)a.c", input: "AXC", outcome: SUCCEED, expr: "found", expected: "AXC" },
  { pattern: "(?i)a.*?c", input: "AXYZC", outcome: SUCCEED, expr: "found", expected: "AXYZC" },
  { pattern: "(?i)a.*c", input: "AXYZD", outcome: FAIL },
  { pattern: "(?i)a[bc]d", input: "ABC", outcome: FAIL },
  { pattern: "(?i)a[bc]d", input: "ABD", outcome: SUCCEED, expr: "found", expected: "ABD" },
  { pattern: "(?i)a[b-d]e", input: "ABD", outcome: FAIL },
  { pattern: "(?i)a[b-d]e", input: "ACE", outcome: SUCCEED, expr: "found", expected: "ACE" },
  { pattern: "(?i)a[b-d]", input: "AAC", outcome: SUCCEED, expr: "found", expected: "AC" },
  { pattern: "(?i)a[-b]", input: "A-", outcome: SUCCEED, expr: "found", expected: "A-" },
  { pattern: "(?i)a[b-]", input: "A-", outcome: SUCCEED, expr: "found", expected: "A-" },
  { pattern: "(?i)a[b-a]", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)a[]b", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)a[", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)a]", input: "A]", outcome: SUCCEED, expr: "found", expected: "A]" },
  { pattern: "(?i)a[]]b", input: "A]B", outcome: SUCCEED, expr: "found", expected: "A]B" },
  { pattern: "(?i)a[^bc]d", input: "AED", outcome: SUCCEED, expr: "found", expected: "AED" },
  { pattern: "(?i)a[^bc]d", input: "ABD", outcome: FAIL },
  { pattern: "(?i)a[^-b]c", input: "ADC", outcome: SUCCEED, expr: "found", expected: "ADC" },
  { pattern: "(?i)a[^-b]c", input: "A-C", outcome: FAIL },
  { pattern: "(?i)a[^]b]c", input: "A]C", outcome: FAIL },
  { pattern: "(?i)a[^]b]c", input: "ADC", outcome: SUCCEED, expr: "found", expected: "ADC" },
  { pattern: "(?i)ab|cd", input: "ABC", outcome: SUCCEED, expr: "found", expected: "AB" },
  { pattern: "(?i)ab|cd", input: "ABCD", outcome: SUCCEED, expr: "found", expected: "AB" },
  { pattern: "(?i)()ef", input: "DEF", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "EF-" },
  { pattern: "(?i)*a", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)(*)b", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)$b", input: "B", outcome: FAIL },
  { pattern: "(?i)a\\", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)a\\(b", input: "A(B", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "A(B-Error" },
  { pattern: "(?i)a\\(*b", input: "AB", outcome: SUCCEED, expr: "found", expected: "AB" },
  { pattern: "(?i)a\\(*b", input: "A((B", outcome: SUCCEED, expr: "found", expected: "A((B" },
  { pattern: "(?i)a\\\\b", input: "A\\B", outcome: SUCCEED, expr: "found", expected: "A\\B" },
  { pattern: "(?i)abc)", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)(abc", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)((a))", input: "ABC", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "A-A-A" },
  { pattern: "(?i)(a)b(c)", input: "ABC", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "ABC-A-C" },
  { pattern: "(?i)a+b+c", input: "AABBABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)a{1,}b{1,}c", input: "AABBABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)a**", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)a.+?c", input: "ABCABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)a.*?c", input: "ABCABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)a.{0,5}?c", input: "ABCABC", outcome: SUCCEED, expr: "found", expected: "ABC" },
  { pattern: "(?i)(a+|b)*", input: "AB", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "AB-B" },
  { pattern: "(?i)(a+|b){0,}", input: "AB", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "AB-B" },
  { pattern: "(?i)(a+|b)+", input: "AB", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "AB-B" },
  { pattern: "(?i)(a+|b){1,}", input: "AB", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "AB-B" },
  { pattern: "(?i)(a+|b)?", input: "AB", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "A-A" },
  { pattern: "(?i)(a+|b){0,1}", input: "AB", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "A-A" },
  { pattern: "(?i)(a+|b){0,1}?", input: "AB", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "-None" },
  { pattern: "(?i))(", input: "-", outcome: SYNTAX_ERROR },
  { pattern: "(?i)[^ab]*", input: "CDE", outcome: SUCCEED, expr: "found", expected: "CDE" },
  { pattern: "(?i)abc", input: "", outcome: FAIL },
  { pattern: "(?i)a*", input: "", outcome: SUCCEED, expr: "found", expected: "" },
  { pattern: "(?i)([abc])*d", input: "ABBBCD", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ABBBCD-C" },
  { pattern: "(?i)([abc])*bcd", input: "ABCD", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ABCD-A" },
  { pattern: "(?i)a|b|c|d|e", input: "E", outcome: SUCCEED, expr: "found", expected: "E" },
  { pattern: "(?i)(a|b|c|d|e)f", input: "EF", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "EF-E" },
  { pattern: "(?i)abcd*efg", input: "ABCDEFG", outcome: SUCCEED, expr: "found", expected: "ABCDEFG" },
  { pattern: "(?i)ab*", input: "XABYABBBZ", outcome: SUCCEED, expr: "found", expected: "AB" },
  { pattern: "(?i)ab*", input: "XAYABBBZ", outcome: SUCCEED, expr: "found", expected: "A" },
  { pattern: "(?i)(ab|cd)e", input: "ABCDE", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "CDE-CD" },
  { pattern: "(?i)[abhgefdc]ij", input: "HIJ", outcome: SUCCEED, expr: "found", expected: "HIJ" },
  { pattern: "(?i)^(ab|cd)e", input: "ABCDE", outcome: FAIL },
  { pattern: "(?i)(abc|)ef", input: "ABCDEF", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "EF-" },
  { pattern: "(?i)(a|b)c*d", input: "ABCD", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "BCD-B" },
  { pattern: "(?i)(ab|ab*)bc", input: "ABC", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ABC-A" },
  { pattern: "(?i)a([bc]*)c*", input: "ABC", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ABC-BC" },
  { pattern: "(?i)a([bc]*)(c*d)", input: "ABCD", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "ABCD-BC-D" },
  { pattern: "(?i)a([bc]+)(c*d)", input: "ABCD", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "ABCD-BC-D" },
  { pattern: "(?i)a([bc]*)(c+d)", input: "ABCD", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "ABCD-B-CD" },
  { pattern: "(?i)a[bcd]*dcdcde", input: "ADCDCDE", outcome: SUCCEED, expr: "found", expected: "ADCDCDE" },
  { pattern: "(?i)a[bcd]+dcdcde", input: "ADCDCDE", outcome: FAIL },
  { pattern: "(?i)(ab|a)b*c", input: "ABC", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "ABC-AB" },
  { pattern: "(?i)((a)(b)c)(d)", input: "ABCD", outcome: SUCCEED, expr: "g1+\"-\"+g2+\"-\"+g3+\"-\"+g4", expected: "ABC-A-B-D" },
  { pattern: "(?i)[a-zA-Z_][a-zA-Z0-9_]*", input: "ALPHA", outcome: SUCCEED, expr: "found", expected: "ALPHA" },
  { pattern: "(?i)^a(bc+|b[eh])g|.h$", input: "ABH", outcome: SUCCEED, expr: "found+\"-\"+g1", expected: "BH-None" },
  { pattern: "(?i)(bc+d$|ef*g.|h?i(j|k))", input: "EFFGZ", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "EFFGZ-EFFGZ-None" },
  { pattern: "(?i)(bc+d$|ef*g.|h?i(j|k))", input: "IJ", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "IJ-IJ-J" },
  { pattern: "(?i)(bc+d$|ef*g.|h?i(j|k))", input: "EFFG", outcome: FAIL },
  { pattern: "(?i)(bc+d$|ef*g.|h?i(j|k))", input: "BCDD", outcome: FAIL },
  { pattern: "(?i)(bc+d$|ef*g.|h?i(j|k))", input: "REFFGZ", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "EFFGZ-EFFGZ-None" },
  { pattern: "(?i)((((((((((a))))))))))", input: "A", outcome: SUCCEED, expr: "g10", expected: "A" },
  { pattern: "(?i)((((((((((a))))))))))\\10", input: "AA", outcome: SUCCEED, expr: "found", expected: "AA" },
  { pattern: "(?i)(((((((((a)))))))))", input: "A", outcome: SUCCEED, expr: "found", expected: "A" },
  { pattern: "(?i)(?:(?:(?:(?:(?:(?:(?:(?:(?:(a))))))))))", input: "A", outcome: SUCCEED, expr: "g1", expected: "A" },
  { pattern: "(?i)(?:(?:(?:(?:(?:(?:(?:(?:(?:(a|b|c))))))))))", input: "C", outcome: SUCCEED, expr: "g1", expected: "C" },
  { pattern: "(?i)multiple words of text", input: "UH-UH", outcome: FAIL },
  { pattern: "(?i)multiple words", input: "MULTIPLE WORDS, YEAH", outcome: SUCCEED, expr: "found", expected: "MULTIPLE WORDS" },
  { pattern: "(?i)(.*)c(.*)", input: "ABCDE", outcome: SUCCEED, expr: "found+\"-\"+g1+\"-\"+g2", expected: "ABCDE-AB-DE" },
  { pattern: "(?i)\\((.*), (.*)\\)", input: "(A, B)", outcome: SUCCEED, expr: "g2+\"-\"+g1", expected: "B-A" },
  { pattern: "(?i)[k]", input: "AB", outcome: FAIL },
  { pattern: "(?i)a[-]?c", input: "AC", outcome: SUCCEED, expr: "found", expected: "AC" },
  { pattern: "(?i)(abc)\\1", input: "ABCABC", outcome: SUCCEED, expr: "g1", expected: "ABC" },
  { pattern: "(?i)([a-c]*)\\1", input: "ABCABC", outcome: SUCCEED, expr: "g1", expected: "ABC" },
  { pattern: "a(?!b).", input: "abad", outcome: SUCCEED, expr: "found", expected: "ad" },
  { pattern: "a(?=d).", input: "abad", outcome: SUCCEED, expr: "found", expected: "ad" },
  { pattern: "a(?=c|d).", input: "abad", outcome: SUCCEED, expr: "found", expected: "ad" },
  { pattern: "a(?:b|c|d)(.)", input: "ace", outcome: SUCCEED, expr: "g1", expected: "e" },
  { pattern: "a(?:b|c|d)*(.)", input: "ace", outcome: SUCCEED, expr: "g1", expected: "e" },
  { pattern: "a(?:b|c|d)+?(.)", input: "ace", outcome: SUCCEED, expr: "g1", expected: "e" },
  { pattern: "a(?:b|(c|e){1,2}?|d)+?(.)", input: "ace", outcome: SUCCEED, expr: "g1 + g2", expected: "ce" },
  { pattern: "(?<!-):(.*?)(?<!-):", input: "a:bc-:de:f", outcome: SUCCEED, expr: "g1", expected: "bc-:de" },
  { pattern: "(?<!\\\\):(.*?)(?<!\\\\):", input: "a:bc\\:de:f", outcome: SUCCEED, expr: "g1", expected: "bc\\:de" },
  { pattern: "(?<!\\?)'(.*?)(?<!\\?)'", input: "a'bc?'de'f", outcome: SUCCEED, expr: "g1", expected: "bc?'de" },
  { pattern: "w(?# comment", input: "w", outcome: SYNTAX_ERROR },
  { pattern: "w(?# comment 1)xy(?# comment 2)z", input: "wxyz", outcome: SUCCEED, expr: "found", expected: "wxyz" },
  { pattern: "(?i)w", input: "W", outcome: SUCCEED, expr: "found", expected: "W" },
  { pattern: "(?x)w# comment 1\n        x y\n        # comment 2\n        z", input: "wxyz", outcome: SUCCEED, expr: "found", expected: "wxyz" },
  { pattern: "^abc", input: "jkl\nabc\nxyz", outcome: FAIL },
  { pattern: "(?m)^abc", input: "jkl\nabc\nxyz", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "(?m)abc$", input: "jkl\nxyzabc\n123", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "\\w+", input: "--ab_cd0123--", outcome: SUCCEED, expr: "found", expected: "ab_cd0123" },
  { pattern: "[\\w]+", input: "--ab_cd0123--", outcome: SUCCEED, expr: "found", expected: "ab_cd0123" },
  { pattern: "\\D+", input: "1234abc5678", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "[\\D]+", input: "1234abc5678", outcome: SUCCEED, expr: "found", expected: "abc" },
  { pattern: "[\\da-fA-F]+", input: "123abc", outcome: SUCCEED, expr: "found", expected: "123abc" },
  { pattern: "([\\s]*)([\\S]*)([\\s]*)", input: " testing!1972", outcome: SUCCEED, expr: "g3+g2+g1", expected: "testing!1972 " },
  { pattern: "(\\s*)(\\S*)(\\s*)", input: " testing!1972", outcome: SUCCEED, expr: "g3+g2+g1", expected: "testing!1972 " },
  { pattern: "\\xff", input: "ÿ", outcome: SUCCEED, expr: "found", expected: "ÿ" },
  { pattern: "\\x00ff", input: "ÿ", outcome: FAIL },
  { pattern: "\\t\\n\\v\\r\\f\\a", input: "\t\n\u000b\r\f\u0007", outcome: SUCCEED, expr: "found", expected: "\t\n\u000b\r\f\u0007" },
  { pattern: "\t\n\u000b\r\f\u0007", input: "\t\n\u000b\r\f\u0007", outcome: SUCCEED, expr: "found", expected: "\t\n\u000b\r\f\u0007" },
  { pattern: "\\t\\n\\v\\r\\f\\a", input: "\t\n\u000b\r\f\u0007", outcome: SUCCEED, expr: "found", expected: "\t\n\u000b\r\f\u0007" },
  { pattern: "[\\t][\\n][\\v][\\r][\\f][\\b]", input: "\t\n\u000b\r\f\b", outcome: SUCCEED, expr: "found", expected: "\t\n\u000b\r\f\b" },
  { pattern: "(([a-z]+):)?([a-z]+)$", input: "smil", outcome: SUCCEED, expr: "g1+\"-\"+g2+\"-\"+g3", expected: "None-None-smil" },
  { pattern: "((.)\\1+)", input: "", outcome: SYNTAX_ERROR },
  { pattern: ".*d", input: "abc\nabd", outcome: SUCCEED, expr: "found", expected: "abd" },
  { pattern: "(", input: "", outcome: SYNTAX_ERROR },
  { pattern: "[\\41]", input: "!", outcome: SUCCEED, expr: "found", expected: "!" },
  { pattern: "(x?)?", input: "x", outcome: SUCCEED, expr: "found", expected: "x" },
  { pattern: "(?x) foo ", input: "foo", outcome: SUCCEED, expr: "found", expected: "foo" },
  { pattern: "(?<!abc)(d.f)", input: "abcdefdof", outcome: SUCCEED, expr: "found", expected: "dof" },
  { pattern: "[\\w-]+", input: "laser_beam", outcome: SUCCEED, expr: "found", expected: "laser_beam" },
  { pattern: ".*?\\S *:", input: "xx:", outcome: SUCCEED, expr: "found", expected: "xx:" },
  { pattern: "a[ ]*?\\ (\\d+).*", input: "a   10", outcome: SUCCEED, expr: "found", expected: "a   10" },
  { pattern: "a[ ]*?\\ (\\d+).*", input: "a    10", outcome: SUCCEED, expr: "found", expected: "a    10" },
  { pattern: "(?ms).*?x\\s*\\z(.*)", input: "xx\nx\n", outcome: SUCCEED, expr: "g1", expected: "" },
  { pattern: "(?i)M+", input: "MMM", outcome: SUCCEED, expr: "found", expected: "MMM" },
  { pattern: "(?i)m+", input: "MMM", outcome: SUCCEED, expr: "found", expected: "MMM" },
  { pattern: "(?i)[M]+", input: "MMM", outcome: SUCCEED, expr: "found", expected: "MMM" },
  { pattern: "(?i)[m]+", input: "MMM", outcome: SUCCEED, expr: "found", expected: "MMM" },
  { pattern: "^*", input: "", outcome: SYNTAX_ERROR },
  { pattern: "\"(?:\\\\\"|[^\"])*?\"", input: "\"\\\"\"", outcome: SUCCEED, expr: "found", expected: "\"\\\"\"" },
  { pattern: "^.*?$", input: "one\ntwo\nthree\n", outcome: FAIL },
  { pattern: "a[^>]*?b", input: "a>b", outcome: FAIL },
  { pattern: "^a*?$", input: "foo", outcome: FAIL },
  { pattern: "^((a)c)?(ab)$", input: "ab", outcome: SUCCEED, expr: "g1+\"-\"+g2+\"-\"+g3", expected: "None-None-ab" },
  { pattern: "^([ab]*?)(?=(b)?)c", input: "abc", outcome: SUCCEED, expr: "g1+\"-\"+g2", expected: "ab-None" },
  { pattern: "^([ab]*?)(?!(b))c", input: "abc", outcome: SUCCEED, expr: "g1+\"-\"+g2", expected: "ab-None" },
  { pattern: "^([ab]*?)(?<!(a))c", input: "abc", outcome: SUCCEED, expr: "g1+\"-\"+g2", expected: "ab-None" }
];

function groupValue(match: RegExpExecArray, name: string): string {
  if (name === "found") return match[0] ?? "";

  const numericGroup = /^g(\d+)$/u.exec(name);
  if (numericGroup) {
    const index = Number.parseInt(numericGroup[1], 10);
    if (index >= match.length) return "Error";
    return match[index] ?? "None";
  }

  return match.groups?.[name] ?? "None";
}

function decodeExpressionString(token: string): string {
  return JSON.parse(token.replace(/^'/u, '"').replace(/'$/u, '"')) as string;
}

function splitPythonExpression(expr: string): string[] {
  const parts: string[] = [];
  let start = 0;
  let quote: string | undefined;
  let escaped = false;

  for (let index = 0; index < expr.length; index += 1) {
    const char = expr[index];
    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === quote) {
        quote = undefined;
      }
      continue;
    }
    if (char === "'" || char === '"') {
      quote = char;
      continue;
    }
    if (char === "+") {
      parts.push(expr.slice(start, index).trim());
      start = index + 1;
    }
  }

  parts.push(expr.slice(start).trim());
  return parts.filter(Boolean);
}

function evaluateTestExpression(expr: string, match: RegExpExecArray): string {
  return splitPythonExpression(expr)
    .map((part) => {
      if (
        (part.startsWith('"') && part.endsWith('"')) ||
        (part.startsWith("'") && part.endsWith("'"))
      ) {
        return decodeExpressionString(part);
      }
      return groupValue(match, part);
    })
    .join("");
}

function runTest(testCase: CpythonReCase) {
  if (testCase.outcome === SYNTAX_ERROR) {
    expect(() => compileEcmaRe(testCase.pattern)).toThrow();
    return;
  }

  let re: RegExp;
  try {
    re = compileEcmaRe(testCase.pattern);
  } catch (error) {
    throw new Error(`Pattern /${testCase.pattern}/ should compile but threw: ${error}`);
  }

  const match = re.exec(testCase.input);
  if (testCase.outcome === FAIL) {
    expect(match).toBeNull();
    return;
  }

  expect(match).not.toBeNull();
  if (!match || testCase.expr === undefined) return;

  expect(evaluateTestExpression(testCase.expr, match)).toBe(testCase.expected);
}

describe("CPython re_tests.py generated port", () => {
  for (const [index, testCase] of CPYTHON_RE_TESTS.entries()) {
    it(`${index}: /${testCase.pattern}/ on ${JSON.stringify(testCase.input)}`, () => {
      runTest(testCase);
    });
  }
});
